# Generated by Django 6.0.1 on 2026-01-17 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Playlist name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Playlist description')),
                ('is_public', models.BooleanField(default=True, help_text='Whether others can view this playlist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Whether to notify subscriber of new uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Video title displayed to users', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Video description (supports markdown in frontend)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('original_file', models.FileField(help_text='Original uploaded video file', null=True, upload_to='videos/original/')),
                ('duration', models.DurationField(blank=True, help_text='Video length (extracted from file)', null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Original file size in bytes', null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', help_text='Current processing status', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', help_text='Who can view this video', max_length=20)),
                ('processing_progress', models.IntegerField(default=0, help_text='Processing completion percentage (0-100)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is FAILED')),
                ('comments_count', models.IntegerField(default=0, help_text='Number of comments (updated via signals)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When video was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification time')),
                ('published_at', models.DateTimeField(blank=True, help_text='When video became publicly available', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Position in playlist (0=first)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_videos', to='video.playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'db_table': 'playlist_videos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Comment content (supports markdown)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Whether comment has been edited')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='video.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video.video')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_name', models.CharField(help_text='Quality label (1080p, 720p, etc.)', max_length=20)),
                ('width', models.IntegerField(help_text='Video width in pixels')),
                ('height', models.IntegerField(help_text='Video height in pixels')),
                ('bitrate', models.CharField(help_text='Target bitrate for encoding', max_length=20)),
                ('file_path', models.CharField(help_text='Path to transcoded MP4 file', max_length=500)),
                ('hls_playlist_path', models.CharField(blank=True, help_text='Path to HLS playlist file (.m3u8)', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Transcoded file size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='video.video')),
            ],
            options={
                'db_table': 'video_qualities',
            },
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', '-created_at'], name='playlists_user_id_eee6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscriber', '-created_at'], name='subscriptio_subscri_93c9db_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['channel'], name='subscriptio_channel_a31120_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'channel')},
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', '-created_at'], name='videos_user_id_5f9058_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='videos_status_510af8_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['visibility', '-published_at'], name='videos_visibil_d07c48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistvideo',
            unique_together={('playlist', 'video')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['video', '-created_at'], name='comments_video_i_adb6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comments_user_id_8613ff_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comments_parent__9f8798_idx'),
        ),
        migrations.AddIndex(
            model_name='videoquality',
            index=models.Index(fields=['video', 'quality_name'], name='video_quali_video_i_7fe23d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoquality',
            unique_together={('video', 'quality_name')},
        ),
    ]
